title: Pretend to Be a Maker
description: The maker blog of Haoxing Zhang 

url: http://haoxingz.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Project
   url: /project
 - title: Travel
   url: /travel
 - title: Food
   url: /food
 - title: About
   url: /about

social:
   github: haoxingz 
   linkedin: 
   facebook: 
   email: haoxing.zhang.david@gmail.com

google_analytics: "UA-72260647-1"
